spring:
  datasource:
    username: root
<<<<<<< Updated upstream
    password: 1998
    url: jdbc:mysql://localhost:3306/jingdong?characterEncoding=UTF-8
=======
    password: Hange666
    url: jdbc:mysql://localhost:3306/jingdong?characterEncoding=utf-8
>>>>>>> Stashed changes
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:org/lanqiao/mapper/*.xml
  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        mapper : debug
