spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/lanqiao
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:org/lanqiao/mapper/*.xml
  type-aliases-package: org.lanqiao.entity

#showSql
logging:
  level:
    org:
      lanqiao:
        mapper : debug
